name: max_gym
description: "max gym application for gym management"
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  supabase_flutter: ^2.8.0
  firebase_core: ^3.4.0
  firebase_crashlytics: ^4.1.0
  firebase_analytics: ^11.4.1
  flutter_local_notifications: ^19.1.0
  path_provider: ^2.1.4
  shared_preferences: ^2.3.0
  pdf: ^3.11.0
  printing: ^5.14.2
  flutter_screenutil: ^5.9.3
  fl_chart: ^0.68.0
  cupertino_icons: ^1.0.8
  intl: ^0.19.0
  flutter_staggered_animations: ^1.1.1
  lottie: ^3.3.1
  vibration: ^3.1.3
  connectivity_plus: ^6.1.4
  animated_text_kit: ^4.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  isar_generator: ^3.1.0+1
  build_runner: ^2.4.12
  flutter_lints: ^5.0.0

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/women.png
    - assets/images/men.png
    - assets/images/max.png
    - assets/locales/en.json
    - assets/locales/fa.json 
    - assets/animations/barabell.json
    - assets/animations/empty_state.json
    - assets/animations/max_gym.gif
    - assets/fonts/Montserrat-Bold.ttf
    - assets/fonts/Montserrat-Regular.ttf
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Bold.ttf
        - asset: assets/fonts/Montserrat-Regular.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
